# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'LAB_ARM'
    subscriptionId: 'a6f84be5-4fb9-4845-8449-756dfc37caa7'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRmPipeline-rg'
    location: 'East US 2'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/heilmats/AzureRmPipeline-repo/main/CreateWebApp/azuredeploy.json?token=GHSAT0AAAAAACBPIBXUZMD3BT7GWLINIJBCZB54MMQ'
    overrideParameters: '-projectName AzureRmPipeline-repo'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
